// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybefnvazeniezrwzpvtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZWZudmF6ZW5pZXpyd3pwdnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDE3MzIsImV4cCI6MjA2MzExNzczMn0.gtiRL-lmOGfGZ_vYL4IU1QS6S7nXM7x6moYrSeuOGj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});