// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hayktjygkwsnbjlrxnab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhheWt0anlna3dzbmJqbHJ4bmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjQzMjQsImV4cCI6MjA2NjgwMDMyNH0.HrPa7p2nCEVOz_GCrjdd3dgXc_wexKmj3lJN6IrsmpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});